### ISSUE TITLE
Instalation guide

### ISSUE THREAD

**Issue by romarioj2h** [lxsang/antos#1]
Can you add a instalation guide to README.md?

**Comment by lxsang** [comment]
I've updated the README.md to describe how to build the API, however, to use it, you need to implement all the system calls of the API in core/handlers/RemoteHandler.coffee with a server side scripting language of your choice. All client/server requests/responses are in **application/json** except the `get` and `shared` system calls which return a raw file

**Comment by romarioj2h** [comment]
Thanks!
